name: Build

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        # Show pre-install environment state
        conda info --quiet
        # Install dependencies to base environment due to lack of persistence between workflow steps
        conda install --quiet -v --yes --name base --channel conda-forge gdal numpy scipy tqdm pytest
        # Show post-install environment state
        conda info --quiet
    - name: Install package with pip
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest -v